### ISSUE TITLE
syringe reporting error for not finding injecting method.

### ISSUE THREAD

**Issue by potterdai** [skylerparr/ex_play_store#1]
When adding ex_play_store as dependency,  syringe injecting method need to be added to global config as well. It seems mix will ignore the config file in dependency folder.
Is there any way to avoid this? like setting default injecting method if not found in config file. Thx!

**Comment by skylerparr** [comment]
Yes! Make sure you update syringe 0.10.8. The default strategy is AliasInjectingStrategy. I hope this works out for you.

**Comment by potterdai** [comment]
It works! Thank you very much! = )
